#ifndef ARCHIVAL_H
#define ARCHIVAL_H

/* Generated by cbindgen — do not edit manually */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef enum ArchivalResult {
    Ok = 0,
    ErrDb = 1,
    ErrNotFound = 2,
    ErrInvalidInput = 3,
    ErrIo = 4,
    ErrJson = 5,
} ArchivalResult;

typedef struct DbHandle DbHandle;

/**
 * Open (or create) an Archival database.
 * Returns NULL on failure; call archival_last_error() for details.
 * db_path and media_root must be valid UTF-8 C strings.
 */
struct DbHandle *archival_db_open(const char *db_path, const char *media_root);

/**
 * Close the database and free the handle. Safe to call with NULL.
 */
void archival_db_close(struct DbHandle *handle);

/**
 * Return the last error message (thread-local). Valid until next call on this thread.
 */
const char *archival_last_error(void);

/**
 * Free a string returned by any archival_* function that outputs a string.
 */
void archival_free_string(char *s);

/**
 * Create a new item of the given category. On success, *out_id is set to a
 * newly allocated UUID string (caller must free with archival_free_string).
 */
enum ArchivalResult archival_item_create(struct DbHandle *handle,
                                         const char *category,
                                         char **out_id);

/**
 * Delete an item and all associated data (cascades via FK).
 */
enum ArchivalResult archival_item_delete(struct DbHandle *handle, const char *item_id);

/**
 * Set fields for an item from a JSON object string.
 * Keys must match sql_column names for the item's category.
 * Unknown keys are ignored. Existing values are overwritten.
 */
enum ArchivalResult archival_item_set_fields(struct DbHandle *handle,
                                             const char *item_id,
                                             const char *fields_json);

/**
 * Get fields for an item as a JSON object string. Caller must free with archival_free_string.
 */
enum ArchivalResult archival_item_get_fields(struct DbHandle *handle,
                                             const char *item_id,
                                             char **out_json);

/**
 * List items, optionally filtered by category. Returns JSON array of item summaries.
 * Each element: {"id":"...","category":"...","created_at":N,"updated_at":N,"notes":...}
 */
enum ArchivalResult archival_items_list(struct DbHandle *handle,
                                        const char *category_filter,
                                        char **out_json);

/**
 * Add a media file reference to an item. file_path is relative to media_root.
 */
enum ArchivalResult archival_media_add(struct DbHandle *handle,
                                       const char *item_id,
                                       const char *relative_path,
                                       const char *mime_type,
                                       int32_t is_primary);

/**
 * List media files for an item. Returns JSON array.
 */
enum ArchivalResult archival_media_list(struct DbHandle *handle,
                                        const char *item_id,
                                        char **out_json);

/**
 * Add a tag to an item (creates the tag if it doesn't exist).
 */
enum ArchivalResult archival_tag_add(struct DbHandle *handle,
                                     const char *item_id,
                                     const char *tag_name);

/**
 * Remove a tag from an item.
 */
enum ArchivalResult archival_tag_remove(struct DbHandle *handle,
                                        const char *item_id,
                                        const char *tag_name);

/**
 * Get tags for an item. Returns JSON array of tag name strings.
 */
enum ArchivalResult archival_tags_for_item(struct DbHandle *handle,
                                           const char *item_id,
                                           char **out_json);

/**
 * Classify an image. Returns JSON: {"category":"Book"}.
 * Caller must free out_json with archival_free_string.
 */
enum ArchivalResult archival_ai_classify(struct DbHandle *_handle,
                                         const char *image_path,
                                         const char *api_key,
                                         char **out_json);

/**
 * Fill category fields from an image via the specialist agent.
 * Returns JSON object of field values. Caller must free with archival_free_string.
 */
enum ArchivalResult archival_ai_fill_fields(struct DbHandle *handle,
                                            const char *item_id,
                                            const char *image_path,
                                            const char *api_key,
                                            char **out_json);

#endif  /* ARCHIVAL_H */
